import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

const projectRoot = process.cwd();
const sourceRoot = path.resolve(projectRoot, '..');
const outputFile = path.join(projectRoot, 'src', 'generated', 'docs.js');

const rootDocPattern = /^(README|\d{2}-.+)\.md$/i;

async function walkMarkdown(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = [];

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await walkMarkdown(fullPath)));
    } else if (entry.isFile() && entry.name.toLowerCase().endsWith('.md')) {
      files.push(fullPath);
    }
  }

  return files;
}

function toPosixPath(value) {
  return value.split(path.sep).join('/');
}

function titleFromMarkdown(markdown, fallback) {
  const frontmatterTitle = markdown.match(/^---\s*[\s\S]*?\ntitle:\s*["']?(.+?)["']?\s*\n[\s\S]*?---/);
  if (frontmatterTitle?.[1]) return frontmatterTitle[1].trim();

  const heading = markdown.split(/\r?\n/).find((line) => /^#\s+/.test(line));
  if (heading) return heading.replace(/^#\s+/, '').trim();

  return fallback
    .replace(/\.md$/i, '')
    .replace(/[-_]/g, ' ')
    .replace(/\b\w/g, (char) => char.toUpperCase());
}

function headingsFromMarkdown(markdown) {
  return markdown
    .split(/\r?\n/)
    .filter((line) => /^#{1,3}\s+/.test(line))
    .map((line) => {
      const [, depth, text] = line.match(/^(#{1,3})\s+(.+)$/);
      return { depth: depth.length, text: text.trim() };
    });
}

async function main() {
  const rootFiles = (await readdir(sourceRoot, { withFileTypes: true }))
    .filter((entry) => entry.isFile() && rootDocPattern.test(entry.name))
    .map((entry) => path.join(sourceRoot, entry.name));

  const productSpecsRoot = path.join(sourceRoot, 'product-specs');
  const productSpecFiles = await walkMarkdown(productSpecsRoot);
  const allFiles = [...rootFiles, ...productSpecFiles].sort((a, b) => a.localeCompare(b));

  const documents = [];

  for (const fullPath of allFiles) {
    const markdown = await readFile(fullPath, 'utf8');
    const relativePath = toPosixPath(path.relative(sourceRoot, fullPath));
    const sourceGroup = relativePath.startsWith('product-specs/') ? 'product-specs' : 'blueprint';

    documents.push({
      id: relativePath.toLowerCase(),
      path: relativePath,
      title: titleFromMarkdown(markdown, path.basename(fullPath)),
      sourceGroup,
      headings: headingsFromMarkdown(markdown),
      content: markdown,
    });
  }

  const body = [
    '/* This file is generated by scripts/generate-content.mjs. */',
    `export const generatedAt = ${JSON.stringify(new Date().toISOString())};`,
    `export const documents = ${JSON.stringify(documents, null, 2)};`,
    '',
  ].join('\n');

  await mkdir(path.dirname(outputFile), { recursive: true });
  await writeFile(outputFile, body, 'utf8');

  console.log(`Generated ${documents.length} Markdown documents at ${toPosixPath(path.relative(projectRoot, outputFile))}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
